version: "3.6"
services:  

  elasticsearch:
    image: harbor.pcce.ce.gov.br/elastic/elasticsearch:8.3.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
        - observability
  kibana:
    image: kibana:8.3.2
    container_name: harbor.pcce.ce.gov.br/elastic/kibana:8.3.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ./kibanadata:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks: 
        - observability

  metricbeat:
    image: harbor.pcce.ce.gov.br/elastic/docker.elastic.co/beats/metricbeat:8.3.2
    container_name: metricbeat
    user: root
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beats/metric/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: on-failure
    networks: 
      - observability

  heartbeat:
    image: harbor.pcce.ce.gov.br/elastic/docker.elastic.co/beats/heartbeat:8.3.2
    container_name: heartbeat
    volumes:      
    - ./beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    environment: 
    - setup.kibana.host=kibana:5601
    networks: 
      - observability

  apm:
    image: harbor.pcce.ce.gov.br/elastic/docker.elastic.co/apm/apm-server-oss:7.17.5
    container_name: apm
    volumes:      
    - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    restart: on-failure
    networks: 
      - observability

networks:
  observability:
    driver: bridge